# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_DIRENC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DIRENC.setGeometry(QtCore.QRect(40, 480, 121, 101))
        self.pushButton_DIRENC.setObjectName("pushButton_DIRENC")
        self.pushButton_AGIRLIK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AGIRLIK.setGeometry(QtCore.QRect(480, 200, 121, 101))
        self.pushButton_AGIRLIK.setObjectName("pushButton_AGIRLIK")
        self.pushButton_AKIM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AKIM.setGeometry(QtCore.QRect(260, 480, 121, 101))
        self.pushButton_AKIM.setObjectName("pushButton_AKIM")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 70, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_HACIM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HACIM.setGeometry(QtCore.QRect(480, 340, 121, 101))
        self.pushButton_HACIM.setObjectName("pushButton_HACIM")
        self.pushButton_FREKANS = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FREKANS.setGeometry(QtCore.QRect(480, 480, 121, 101))
        self.pushButton_FREKANS.setObjectName("pushButton_FREKANS")
        self.pushButton_SICAKLIK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SICAKLIK.setGeometry(QtCore.QRect(260, 200, 121, 101))
        self.pushButton_SICAKLIK.setObjectName("pushButton_SICAKLIK")
        self.pushButton_ALAN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ALAN.setGeometry(QtCore.QRect(260, 340, 121, 101))
        self.pushButton_ALAN.setObjectName("pushButton_ALAN")
        self.pushButton_ZAMAN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ZAMAN.setGeometry(QtCore.QRect(40, 200, 121, 101))
        self.pushButton_ZAMAN.setObjectName("pushButton_ZAMAN")
        self.pushButton_UZUNLUK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_UZUNLUK.setGeometry(QtCore.QRect(40, 340, 121, 101))
        self.pushButton_UZUNLUK.setObjectName("pushButton_UZUNLUK")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 200, 121, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\Users\Eren\OneDrive\Masaüstü\istockphoto-1409705164-612x612.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_DIRENC.setText(_translate("MainWindow", "DİRENÇ"))
        self.pushButton_AGIRLIK.setText(_translate("MainWindow", "AĞIRLIK"))
        self.pushButton_AKIM.setText(_translate("MainWindow", "AKIM"))
        self.label.setText(_translate("MainWindow", "BİRİM DÖNÜŞTÜRÜCÜ"))
        self.pushButton_HACIM.setText(_translate("MainWindow", "HACİM"))
        self.pushButton_FREKANS.setText(_translate("MainWindow", "FREKANS"))
        self.pushButton_SICAKLIK.setText(_translate("MainWindow", "SICAKLIK"))
        self.pushButton_ALAN.setText(_translate("MainWindow", "ALAN"))
        self.pushButton_ZAMAN.setText(_translate("MainWindow", "ZAMAN"))
        self.pushButton_UZUNLUK.setText(_translate("MainWindow", "UZUNLUK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
